spring:
  application:
    name: service-consul-obtain
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-consul-obtain
        prefer-ip-address: true
server:
  port: 8505