server:
  port: 8030
spring:
  application:
    name: microservice-consumer
eureka:
  client:
    service-url:
#      defaultZone: http://root:root@eureka1:8000/eureka/,http://root:root@eureka2:8001/euerka/
      defaultZone: http://root:root@192.168.74.130:8000/eureka/
#      defaultZone: http://root:root@localhost:8000/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.service.consumer.feign.UserFeignClient: DUBUG

feign:
  hystrix:
    enabled: true
