spring:
  application:
    name: microservice-service-obtain

server:
  port: 8060

eureka:
  client:
    service-url:
      #      defaultZone: http://root:root@eureka1:8000/eureka/,http://root:root@eureka2:8001/euerka/
      #      defaultZone: http://root:root@192.168.74.130:8000/eureka/
      defaultZone: http://root:root@localhost:8000/eureka/
  instance:
    prefer-ip-address: true