spring:
  application:
    name: service-consul-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-consul-provider
server:
  port: 8501

