spring:
  application:
    name: service-consul-provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: service-consul-provider
        prefer-ip-address: true
        tags: version=1.0,author=liulei
        healthCheckPath: /info.json
        healthCheckInterval: 5s
server:
  port: 8501



