server:
  port: 8040

spring:
  application:
    name: microservice-hystrix-turbine

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:8000/eureka/
      defaultZone: http://root:root@192.168.74.130:8000/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: microservice-consumer,microservice-provider-user
  clusterNameExpression: "'default'"